# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'Attention Madness' 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jbpayne.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jaibpayne
github_username:  jbpyn
show_excerpts: true
timezone: Pacific/Auckland

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-relative-links]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

description:	     'A micro.blog'
author:              'J.B Payne'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
feed:
path: rss-feed.xml
